-include onnx_tts.dep
onnx_tts.lo: /home/decodo/work/onnx-php/php-ext/onnx_tts.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/decodo/work/onnx-php/php-ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /home/decodo/work/onnx-php/php-ext/onnx_tts.c -o onnx_tts.lo  -MMD -MF onnx_tts.dep -MT onnx_tts.lo
$(phplibdir)/onnx_tts.la: ./onnx_tts.la
	$(LIBTOOL) --tag=CC --mode=install cp ./onnx_tts.la $(phplibdir)

./onnx_tts.la: $(shared_objects_onnx_tts) $(ONNX_TTS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_onnx_tts) $(ONNX_TTS_SHARED_LIBADD)

